syntax = "proto3";

package chat;

option go_package = "chat.v1;chatv1";

service Chat {
    // ---------------------------------------------------------------------
    //                              Chats
    // ---------------------------------------------------------------------

    rpc CreateChat(CreateChatRequest) returns (Chat);

    rpc DeleteChat(DeleteChatRequest) returns (Empty);

    rpc UpdateChat(UpdateChatRequest) returns (Chat);

    rpc ListUserChats(ListUserChatsRequest) returns (ListUserChatsResponse);

    // ---------------------------------------------------------------------
    //                           Invite links
    // ---------------------------------------------------------------------

    rpc CreateInviteLink(CreateInviteLinkRequest) returns (InviteLink);

    rpc JoinChatByInvite(JoinChatByInviteRequest) returns (Chat);
}

// ---------------------------------------------------------------------
//                              Chats
// ---------------------------------------------------------------------

message CreateChatRequest {

}

message DeleteChatRequest {

}

message UpdateChatRequest {

}

message ListUserChatsRequest {

}

message ListUserChatsResponse {

}

message Chat {

}

// ---------------------------------------------------------------------
//                           Invite links
// ---------------------------------------------------------------------

message CreateInviteLinkRequest {

}

message InviteLink {

}

message JoinChatByInviteRequest {
    
}

message JoinChatByInviteResponse {
    
}

// ---------------------------------------------------------------------
//                               Other
// ---------------------------------------------------------------------

message Empty {
    
}