syntax = "proto3";

package chat;

option go_package = "chat.v1;chatv1";

service Chat {
    // ---------------------------------------------------------------------
    //                              Chats
    // ---------------------------------------------------------------------

    rpc CreateChat(CreateChatRequest) returns (CreateChatResponse);

    rpc DeleteChat(DeleteChatRequest) returns (DeleteChatResponse);

    rpc UpdateChat(UpdateChatRequest) returns (UpdateChatResponse);

    rpc ListUserChats(ListUserChatsRequest) returns (ListUserChatsResponse);

    // ---------------------------------------------------------------------
    //                           Invite links
    // ---------------------------------------------------------------------

    rpc CreateInviteLink(CreateInviteLinkRequest) returns (CreateInviteLinkResponse);

    rpc JoinChatByInvite(JoinChatByInviteRequest) returns (JoinChatByInviteResponse);
}

// ---------------------------------------------------------------------
//                              Chats
// ---------------------------------------------------------------------

message CreateChatRequest {

}

message CreateChatResponse {
    
}

message DeleteChatRequest {

}

message DeleteChatResponse {

}

message UpdateChatRequest {

}

message UpdateChatResponse {

}

message ListUserChatsRequest {

}

message ListUserChatsResponse {

}

// ---------------------------------------------------------------------
//                           Invite links
// ---------------------------------------------------------------------

message CreateInviteLinkRequest {

}

message CreateInviteLinkResponse {

}

message JoinChatByInviteRequest {
    
}

message JoinChatByInviteResponse {
    
}