syntax = "proto3";

package chat;

option go_package = "chat.v1;chatv1";

service Chat {
    // ---------------------------------------------------------------------
    //                              Chats
    // ---------------------------------------------------------------------

    rpc CreateChat(CreateChatRequest) returns (Chat);

    rpc DeleteChat(DeleteChatRequest) returns (Empty);

    rpc UpdateChat(UpdateChatRequest) returns (Chat);

    rpc ListUserChats(ListUserChatsRequest) returns (ListUserChatsResponse);

    // ---------------------------------------------------------------------
    //                           Invite links
    // ---------------------------------------------------------------------

    rpc CreateInviteLink(CreateInviteLinkRequest) returns (InviteLink);

    rpc JoinChatByInvite(JoinChatByInviteRequest) returns (Chat);
}

// ---------------------------------------------------------------------
//                              Chats
// ---------------------------------------------------------------------

message CreateChatRequest {
    string type = 1; // cloud private, e2e private, group
    optional string title = 2; // for groups
}

message DeleteChatRequest {

}

message UpdateChatRequest {

}

message ListUserChatsRequest {

}

message ListUserChatsResponse {

}

message Chat {
    int64 id = 1; // chat id
    string type = 2; // cloud private, e2e private, group
    optional string title = 3; // for groups
    int64 created_by = 4; // id of user who has created this chat
    repeated int64 admin_ids = 5; // ids of admins
}

// ---------------------------------------------------------------------
//                           Invite links
// ---------------------------------------------------------------------

message CreateInviteLinkRequest {

}

message InviteLink {

}

message JoinChatByInviteRequest {
    
}

message JoinChatByInviteResponse {
    
}

// ---------------------------------------------------------------------
//                               Other
// ---------------------------------------------------------------------

message Empty {

}